### ISSUE TITLE
Great idea

### ISSUE THREAD

**Issue by sysmat** [danmt/dynamic-component-loader#1]
I try to use it in my ivy 9 app but no successes. In AppService  I see that pipe is not triggered
so component is not rendered.

My scenarion:
-  ViewChild and Directive is avalable
- from function I trigger loadComponent
```typescript
loadDan1() {
    const viewContainerRef = this.cmpHost.viewContainerRef;
    this.loader.loadComponent(viewContainerRef, Cmp.DAN1);
    this.title = 'title bind dan 1';
  }
```
- loader service:: loadComponent is executed
```typescript
loadComponent(vcr: ViewContainerRef, enum: Cmp) {
    vcr.clear();
    console.log('loadComp:enum', enum);
    return this.appService.forChild(vcr, { loadChildren: this.yeald(enum) });
}
```  
- service:: private func is executed

```typescript
private dan1() {
    console.log('private dan1 func');
    return () => import('./dan1/dan1.component').then(m => m.Dan1Component);
  }
```
- app service::forChild is executed, but pipe is not 
```typescript
forChild(vcr: ViewContainerRef, cl: ComponentLoader) {
    console.log('forChild')
    return from(cl.loadChildren())
      .pipe(
        tap(() => console.log('loadChildren pipe')),
        map((component: any) => this.cfr.resolveComponentFactory(component)),
        map(componentFactory => vcr.createComponent(componentFactory))
      );
  }
```
Last pipe is never trigger I'm missing something?

Regards, Tomaž

**Comment by sysmat** [comment]
It seam that rxjs _from_ Promise not working, if I use directly on Promise it works 

```typescript
cl.loadChildren()
  .then((component: any) => this.cfr.resolveComponentFactory(component))
  .then(componentFactory => vcr.createComponent(componentFactory))
```

Any idea why?

Regars, Tomaž

**Comment by danmt** [comment]
Hello Tomaž, 

I think the problem is related to a lack of subscription. The `forChild` method is called and it triggers the `console.log`, since it returns an RxJs Observable (they are lazy by nature and they aren't called until you subscribe). What you need to do is call it this way: 

```typescript
forChild(vcr, cl)
  .subscribe((componentInstance) => {
    // Here you can manipulate the component instance
  })
```

Take a look at this https://github.com/danmt/dynamic-component-loader/blob/master/src/app/profile/profile.service.ts#L34 my loadComponent is wrapping the appService method, then look at this https://github.com/danmt/dynamic-component-loader/blob/master/src/app/profile/profile.component.ts#L23 I'm calling the method inside `mergeMap` which does the subscription for me.

Hope that helps,
Daniel M.

**Comment by sysmat** [comment]
Yes, that was the problem, thx I like your post and idea.

Regards, Tomaž
